### ISSUE TITLE
All samples fail, when using cuda, on OSX 10.11 with latest Cuda 8, SBCL 1.3.1 x64, cl-cuda from git

### ISSUE THREAD

**Issue by atomontage** [takagi/avm#44]
Same condition on all:

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1002ACC683}>:
  The function COERCE is undefined.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(CL-CUDA.LANG.BUILT-IN::INFERRED-FUNCTION-CANDIDATES COERCE)

When running on CPU all is fine.

**Comment by takagi** [comment]
Thanks for reporting. Something should be wrong, I will check it.

**Comment by takagi** [comment]
Fixed via https://github.com/takagi/cl-cuda/commit/0df19d5b2beb032fa22fde948e5aca1cd7fa283f and https://github.com/takagi/avm/commit/c6d3c622d21ee3df3e53937df3c8c266abd1d106.
